### ISSUE TITLE
Limiting number of containers?

### ISSUE THREAD

**Issue by kossmoboleat** [jenkinsci/docker-swarm-plugin#16]
I couldn't find a documentation if it's possible to limit the number of instances of a specific template. 

I'd like to limit each of our two dozen different slaves to a specific value. Ideally we'd also like to limit the overall number of concurrently running docker slaves. The "regular" Docker plugin has this ability.

**Comment by Roemer** [comment]
As mentioned, reservations can be used to reserve CPU and/or RAM on the swarm nodes. I think this provides enough flexibility to limit the containers. If not please re-open the ticket with further information on your scenario.
