### ISSUE TITLE
Provide the way to set user that runs job.

### ISSUE THREAD

**Issue by Likebutter** [jenkinsci/docker-swarm-plugin#19]
It will be great to have the possibility to set user who will execute job for swarm cloud. Currently, when connecting via jnlp agent, java process is executed as root. Here is the way that this is done in yad plugin:
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher/init.sh#L112
https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/java/com/github/kostyasha/yad/launcher/DockerComputerJNLPLauncher.java#L367

**Comment by gaelrottier** [comment]
Anyway it's a really bad practice to launch a container as root, furthermore on a container cluster. YAD should not do that, and should prevent you from doing such a thing.

**Comment by Roemer** [comment]
I guess that PR fixed the issue mentioned here. Otherwise please re-open that ticket with further information.
