### ISSUE TITLE
Allow using a custom workspace on the agent

### ISSUE THREAD

**Issue by gaelrottier** [jenkinsci/docker-swarm-plugin#22]
The Docker image I use to run the agent is not run as root, and I don't want to execute my pipeline in `tmp`directory.
I need to specify a custom directory which I created while building the image.

**Comment by smhc** [comment]
https://github.com/smhc/docker-swarm-plugin-tls supports custom workspaces

It'd be great if PR https://github.com/jenkinsci/docker-swarm-plugin/pull/1 was merged, it contains a lot of fixes and enhancements.

**Comment by gaelrottier** [comment]
Oh thanks, I also see you handle secrets and credentials, I will need it later :)

**Comment by gaelrottier** [comment]
@smhc my prs have just been merged, I think you should rebase your work so your pr can be merged :)

**Comment by smhc** [comment]
I've rebased the changes for PR https://github.com/jenkinsci/docker-swarm-plugin/pull/1 
Any chance of a merge?
