### ISSUE TITLE
Please add envvar with agent name

### ISSUE THREAD

**Issue by gutschet** [jenkinsci/docker-swarm-plugin#37]
Currently, the plugin creates three environment variables:
* $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_SECRET
* $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JAR_URL
* $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_JNLP_URL

I want to use it with the jenkins/jnlp-slave Docker Image, but I need to pass the image the name of the agent. Therefor it would be great if you could add an additional environment variable like 
* $DOCKER_SWARM_PLUGIN_JENKINS_AGENT_NAME

**Comment by Roemer** [comment]
Could you try the changes from #39 if that works for you?

**Comment by gutschet** [comment]
Great, that is exactly what I imagined. Now the plugin can be used with jenkins/jnlp-slave easily.

**Comment by Roemer** [comment]
The PR is merged now.
