### ISSUE TITLE
More docs

### ISSUE THREAD

**Issue by Crocmagnon** [jenkinsci/docker-swarm-plugin#6]
Please provide more docs (or links to docs) about :

- [ ] where to find the configuration options
- [ ] each field
- [ ] how to troubleshoot the error messages
- [ ] what steps are required on the swarm manager to accept connections
- [ ] how to provide certificates to the plugin so it can use tls in both ways (client and server auth)
- [ ] how to use the declared agents

**Comment by smhc** [comment]
PR https://github.com/jenkinsci/docker-swarm-plugin/pull/1 adds support for client certificates using TLS.
It also adds documentation for many fields.

**Comment by Roemer** [comment]
Most of the things are documented now. If anything is still missing, please re-open a new ticket.
