### ISSUE TITLE
Allow passing credentials for private registry

### ISSUE THREAD

**Issue by Crocmagnon** [jenkinsci/docker-swarm-plugin#8]
I need to use custom images from private registry which needs credentials to pull.

**Comment by Roemer** [comment]
This is very much needed. Also I saw that the normal docker plugin (https://github.com/jenkinsci/docker-plugin) supports that and it seems to be implemented a bit nicer than in your PR.

**Comment by Roemer** [comment]
This is implemented now. It uses Jenkins credentials for username/password.
