### ISSUE TITLE
Multiple Labels

### ISSUE THREAD

**Issue by wassy92x** [jenkinsci/docker-swarm-plugin#96]
If I setup a docker swarm cloud, add an template for an service / container and set multiple labels for this template, Jenkins can't find a this node.

For example I set the following labels to the template: "docker_cloud_agent linux"
and setup the following Jenkinsfile
`node('linux') {
   echo 'Hello World'
}`
Jenkins can't find an agent with label "linux"

Jenkins-Version: 2.249.3
Docker-Swarm-Plugin-Version: 1.9 (I also tried a self compile version of the current master-branch)

**Comment by Nuh** [comment]
Implementented in PR #97
